# This config.ini file supports usage of environment variables for for STRING-type parameters on Windows and POSIX/Linux based systems
# E.g. $HOME or $AXL_PASS (POSIX/Linux) / %HOME% or %AXL_PASS% (Windows)
# Parameters may contain references using this format to dynamically load values from environment variables

###################################
###       GLOBAL SETTINGS       ###
###################################

[settings]
; OUTPUT_DESTINATION = email
; PATTERN_TYPES = enterprise
; INCLUDE_ELAPSED_TIME = false
; SEVERITY_LEVEL = informational
; MAX_RESULTS = 500000
; MAX_SAMPLES = 10
; CERT_PATH = /path/to/cacert.pem
; USE_PRETTY_PRINT = true

[logging]
; LOG_RETENTION = 90
; LOG_FILE_DIR = /var/log/

# SMTP settings only used if OUTPUT_DESTINATION is 'email' or 'both'
[smtp]
; SMTP_SERVER = smtp.example.com
; SMTP_PORT = 25
; SMTP_FROM = DoNotReply@example.com
; SMTP_TO = someone@example.com

###################################
### CUCM CLUSTER CONFIGURATIONS ###
###################################

# Sample A CUCM cluster configiration
; [cucm_cluster_a]
; LABEL = Cluster A
; FQDN = clus-a.example.com
; AXL_USER = cucm_axl_user
; AXL_PASS = $CUCM_AXL_PASS
; IGNORE_PATTERNS = 10XXX, *10XXX

# Sample B CUCM cluster configiration
; [cucm_cluster_b]
; LABEL = Cluster B
; FQDN = clus-b.example.com
; AXL_USER = cucm_axl_user
; AXL_PASS = $CUCM_AXL_PASS
; IGNORE_PATTERNS = 210XX

# Sample C CUCM cluster configiration
; [cucm_cluster_c]
; LABEL = Cluster C
; FQDN = clus-c.example.com
; AXL_USER = cucm_axl_user
; AXL_PASS = $CUCM_AXL_PASS
; VERIFY_CERT = false